### ISSUE TITLE
undefined method ChangeCurrency()

### ISSUE THREAD

**Issue by 0xMurage** [tnkemdilim/Money-To-Words-Converter#6]
Method MoneyToWords\MoneyToWordsConverter::ChangeCurrency() is undefined. An exception is thrown when one tries to access the method.

**Comment by toksdotdev** [comment]
Checking it out

**Comment by toksdotdev** [comment]
This has been fixed in the latest updates. To change currency, see [How to change currency](https://github.com/TNkemdilim/Money-To-Words-Converter#change-language-translation).

This would be available in the `v2.0.0` release since there are breaking changes.

Thanks a lot filing this issue.

I'll be closing this then.
