### ISSUE TITLE
accuracy

### ISSUE THREAD

**Issue by 0xMurage** [tnkemdilim/Money-To-Words-Converter#7]
The conversion is not accurate. Try converting "50000400" to English language 🤦

**Comment by toksdotdev** [comment]
On it.

**Comment by toksdotdev** [comment]
The accuracy of conversion has been worked upon. I had to change the approach of generating the sentence. The new approach is more accurate.

Although it would be available from `v2.0.0` release since there are breaking changes.

Thanks a lot filing this issue.

I'll be closing this. Please free to open it, if any in-accuracy still exist.
