### ISSUE TITLE
missing libraries

### ISSUE THREAD

**Issue by 0xMurage** [tnkemdilim/Money-To-Words-Converter#8]
There are missing libraries in the composer.json file (while are mysteriously available in composer.lock file). Update the required dependencies in composer.json

**Comment by toksdotdev** [comment]
Just fixed this. Thanks a lot 🚀🚀🚀.

**Comment by 0xMurage** [comment]
You have not updated the composer.json file to include
> "guzzlehttp/promises": "^1.0",
> "guzzlehttp/psr7": "^1.4",

**Comment by toksdotdev** [comment]
I dont need to update the composer.json file. The reason is because I am only leveraging on ``` stichoza/google-translate-php```, and this is a level 0 dependency.

The other dependencies you are seeing in composer.lock file are the dependencies of ```stichoza/google-translate-php```. The reason why they are in composer.lock, is to lock down version numbers of those libraries, and prevent any breaking changes that might have occured to affect any aspect of this code base.

Thats the difference between composer.lock and composer.json.

Not all dependencies in composer.lock are in composer.json. 

Only level 0 dependencies get added to composer.json
